project:
  type: website
  output-dir: docs

website:
  title: "Yicong Zeng"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - life.qmd
      - portfolio.qmd

format:
  html:
    theme: litera
    css: styles.scss
    toc: true
    mainfont: Times
    page-layout: full

editor: visual
